### ISSUE TITLE
Panic if use func that return interface in "where" clause

### ISSUE THREAD

**Issue by inhuman** [newm4n/grool#8]
**Describe the bug**
Panic if use func that return interface in "where" clause

**To Reproduce**
```
package examples

import (
	"github.com/newm4n/grool/builder"
	"github.com/newm4n/grool/context"
	"github.com/newm4n/grool/engine"
	"github.com/newm4n/grool/model"
	"github.com/newm4n/grool/pkg"
	"testing"
)

const (
	Rule81 = `
rule UserTestRule8 "test 8"  salience 10{
	when
	  User.GetParam() == "string_param"
	then
	  User.SetName("FromRule");
	  Retract("UserTestRule8");
}
`
	Rule82 = `
rule UserTestRule8 "test 8"  salience 10{
	when
	  User.GetParam() == 42
	then
	  User.SetName("FromRule");
	  Retract("UserTestRule8");
}
`
)

type AUserIssue8 struct {
	Name  string
	Param interface{}
	Age   int
}

func (u *AUserIssue8) GetName() string {
	return u.Name
}

func (u *AUserIssue8) GetParam() interface{} {
	return u.Param
}

func (u *AUserIssue8) SetName(name interface{}) {
	u.Name = name.(string)
}

func TestMethodCall_Issue8_1(t *testing.T) {
	user := &AUserIssue8{
		Name: "Watson",
		Age:  7,
		Param: "string_param",
	}

	dataContext := context.NewDataContext()
	err := dataContext.Add("User", user)
	if err != nil {
		t.Fatal(err)
	}

	knowledgeBase := model.NewKnowledgeBase()
	ruleBuilder := builder.NewRuleBuilder(knowledgeBase)

	err = ruleBuilder.BuildRuleFromResource(pkg.NewBytesResource([]byte(Rule81)))
	if err != nil {
		t.Log(err)
	} else {
		eng1 := &engine.Grool{MaxCycle: 5}
		err := eng1.Execute(dataContext, knowledgeBase)
		if err != nil {
			t.Fatal(err)
		}
		if user.GetName() != "FromRule" {
			t.Errorf("User should be FromRule but %s", user.GetName())
		}
	}
}

func TestMethodCall_Issue8_2(t *testing.T) {
	user := &AUserIssue8{
		Name: "Watson",
		Age:  7,
		Param: 42,
	}

	dataContext := context.NewDataContext()
	err := dataContext.Add("User", user)
	if err != nil {
		t.Fatal(err)
	}

	knowledgeBase := model.NewKnowledgeBase()
	ruleBuilder := builder.NewRuleBuilder(knowledgeBase)

	err = ruleBuilder.BuildRuleFromResource(pkg.NewBytesResource([]byte(Rule82)))
	if err != nil {
		t.Log(err)
	} else {
		eng1 := &engine.Grool{MaxCycle: 5}
		err := eng1.Execute(dataContext, knowledgeBase)
		if err != nil {
			t.Fatal(err)
		}
		if user.GetName() != "FromRule" {
			t.Errorf("User should be FromRule but %s", user.GetName())
		}
	}
}

```
```
=== RUN   TestMethodCall_Issue8
--- FAIL: TestMethodCall_Issue8 (0.00s)
panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value

goroutine 19 [running]:
testing.tRunner.func1(0xc0000e4a00)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x866820, 0xc00023fa80)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.Type(0x0, 0x0, 0x0, 0x98, 0x0)
	/usr/local/go/src/reflect/value.go:1877 +0x166
github.com/newm4n/grool/model.(*Predicate).Evaluate(0xc0001f7600, 0xc00011d920, 0x1, 0x0, 0xc0002281b0, 0xc000195c60)
	/home/id/hdd/go-nogopath/src/github.com/newm4n/grool/model/Predicate.go:104 +0x1845
github.com/newm4n/grool/model.(*Expression).Evaluate(0xc0001f75c0, 0x0, 0xd11df0, 0x861760, 0xc000256008, 0xc00011d950)
	/home/id/hdd/go-nogopath/src/github.com/newm4n/grool/model/Expression.go:53 +0x460
github.com/newm4n/grool/model.(*WhenScope).ExecuteWhen(0xc00023f760, 0x410763, 0xc000195e60, 0xd11df0)
	/home/id/hdd/go-nogopath/src/github.com/newm4n/grool/model/WhenScope.go:41 +0x32
github.com/newm4n/grool/model.(*RuleEntry).CanExecute(0xc0000a7e60, 0xc00011d950, 0xc000195e60, 0xd11df0)
	/home/id/hdd/go-nogopath/src/github.com/newm4n/grool/model/RuleEntry.go:48 +0x39
github.com/newm4n/grool/engine.(*Grool).Execute(0xc000195f08, 0xc00011d920, 0xc0000a5650, 0x0, 0x0)
	/home/id/hdd/go-nogopath/src/github.com/newm4n/grool/engine/GroolEngine.go:58 +0x1c6
github.com/newm4n/grool/examples.TestMethodCall_Issue8(0xc0000e4a00)
	/home/id/hdd/go-nogopath/src/github.com/newm4n/grool/examples/Issue8_test.go:63 +0x337
testing.tRunner(0xc0000e4a00, 0x918a08)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350

Process finished with exit code 1
```
**Expected behavior**
Rule works correctly

**Comment by newm4n** [comment]
If `User.GetParam()` is returning an interface, even go can't compare them directly since an `interface` could be anything. You have to cast the interface to their type like `User.GetParam().(string) == "somestring"` for the comparison to work. Right now, Grool's syntax and grammar don't support this. And I don't intend to implement all Golang's syntaxis capabilities into Grool. In my opinion, the grool rule script should be made simple and straight forward.

**Comment by inhuman** [comment]
ok thx
